### PR TITLE
Fix wrong anchor

### PR DESCRIPTION
**Pull request by khaosdoctor**
**What this PR does / why we need it**:

In the docs, there's a link to a scripting tutorial, but it points back to the intro where the user just came from. This PR points the link to the right scripting guide.

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by khaosdoctor** [comment]
Fixed DCO

**Comment by krancour** [comment]
Thanks @khaosdoctor !

**Comment by krancour** [comment]
The test that's failing is entirely unrelated to this change.

@khaosdoctor in looking at this PR closer, I don't believe the original link was an error.

The intent here, as I understand it, was not to link to the comprehensive scripting guide; rather to link to a tutorial that, among other things, gives the user their first introduction to scripting in Brigade.

cc @vdice wdyt?

**Comment by vdice** [comment]
> cc @vdice wdyt?

I'm not sure what the original intention was, but I think I agree with @khaosdoctor that it might make more sense to link to the scripting guide proper instead of back to the intro here.

**Comment by krancour** [comment]
@vdice @khaosdoctor 

I'd be fine with linking to the scripting guide we think that makes more sense, but if we do that, imho, the wording should change in addition to the link:

> Moreover, you can check out [this tutorial](https://docs.brigade.sh/topics/scripting/) for more on creating scripts.

☝️  The scripting guide isn't organized like a _tutorial._

Perhaps something like the following works?

> Moreover, you can check out [our scripting guide](https://docs.brigade.sh/topics/scripting/) for more on creating scripts.

**Comment by khaosdoctor** [comment]
> @vdice @khaosdoctor
> 
> I'd be fine with linking to the scripting guide we think that makes more sense, but if we do that, imho, the wording should change in addition to the link:
> 
> > Moreover, you can check out [this tutorial](https://docs.brigade.sh/topics/scripting/) for more on creating scripts.
> 
> ☝️ The scripting guide isn't organized like a _tutorial._
> 
> Perhaps something like the following works?
> 
> > Moreover, you can check out [our scripting guide](https://docs.brigade.sh/topics/scripting/) for more on creating scripts.

I like this idea too, let me create this change

**Review by krancour — APPROVED** [review]
Thanks @khaosdoctor!

LGTM

**Comment by krancour** [comment]
Merging without CI as maintainers have agreed that doc changes don't require the full test suite to run.

**Pull request merged**
