### PR TITLE
fix permissions requirments for creating events

### LINKED ISSUE #1769: bug: Overly restrictive permissions check when creating project-specific events
At present, an `EVENT_CREATOR` with appropriate scope (source) can create events that are not project-specific.

To create project-specific events requires the `PROJECT_USER` role for the project in question.

This is too restrictive for gateways that rightfully wish to emit and event that is only for consumption by a given project.

A very good example of this is a `check_run:rerequested` webhook from GitHub, which becomes a `check_run:rerequested` event sent to Brigade. Because the check in question would have been created _by_ a specific Brigade project, that same specific Brigade project should be the only recipient of that `check_run:rerequested` event.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #1769

### CODE REVIEW

**Review by vdice — APPROVED** [review]
Changes LGTM; pending CI passing.

**Comment by krancour** [comment]
Worker build keeps timing out. I'm speculating that there may be something going on with npmjs.org.

/brig run

**Comment by krancour** [comment]
> I'm speculating that there may be something going on with npmjs.org.

And no sooner did I write that than the status page finally reflected the issue.

**Pull request merged**
