### PR TITLE
Copy docs site from v1

### LINKED ISSUE #1412: v1/v2 doc site plans?
Is there a plan for how to roll out docs for v2 while still preserving the existing documentation for v1 until v1 is deprecated? I would like to help contribute to documentation for v2, such as quickstarts or tutorials. If there isn't a spot for it yet, I'm happy to help figure out a transition plan.

cc @flynnduism

### PR DESCRIPTION
**Pull request by carolynvs**
**What this PR does / why we need it**:
Copy the docs site from the default branch into the v2 branch so that we can start customizing it for the v2 launch of Brigade.

I have added a makefile target, `make docs-preview`, that render the site and launch it in your web browser.

Closes #1412 

**Special notes for your reviewer**:
* This does not customize the copied v1 docs site. That will come in later pull request. This is just enough to give me something to work against in Netlify, and continue configuring.
* I'm unsure if merging this back into master eventually will be a pain, because the docs files lost their revision history and git thinks they are net new. 🤷‍♀️ That ship has long since sailed though!
* @flynnduism I ended up not using the separate netlify site, and instead added the v2 branch as one of the branches that should be deployed (in addition to master). The staging site url for the v2 docs will be located at https://v2--brigade-docs.netlify.app once we merge this.

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by flynnduism** [comment]
/lgtm @carolynvs! Thanks

---

> I'm unsure if merging this back into master eventually will be a pain, because the docs files lost their revision history and git thinks they are net new. 🤷‍♀️ That ship has long since sailed though! 

Yes `master` and `v2` are too divergent, docs aside the whole codebase is changed

> @flynnduism I ended up not using the separate netlify site, and instead added the v2 branch as one of the branches that should be deployed (in addition to master). The staging site url for the v2 docs will be located at https://v2--brigade-docs.netlify.app once we merge this.

Perfect, the branch deploy you've deployed works great.

**Review by radu-matei — COMMENTED** [review]
Given that I assume the docs will be entirely different for v2, not keeping history should not be an issue.

**Review by radu-matei — APPROVED** [review]

**Comment by krancour** [comment]
> I'm unsure if merging this back into master eventually

I'm not sure we've ever planned to merge v2 into master. More likely, v2 becomes the main branch and master is renamed to v1. Something like that...

**Comment by krancour** [comment]
Also lgtm, too.

**Pull request merged**
