### PR TITLE
Add project contributor ladder

### PR DESCRIPTION
**Pull request by karenhchu**
Signed-off-by: Karen Chu <karen.chu@microsoft.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by carolynvs — COMMENTED** [review]
Can we link to this from the Contributing guide?

**Comment by carolynvs** [comment]
I will never be able to spell some words, committtmenet is one of them. 😀

**Comment by radu-matei** [comment]
Question - do we want to have this sort of document in the community repo - https://github.com/brigadecore/community ?

Otherwise, LGTM, thanks a lot for this!

**Comment by karenhchu** [comment]
Hm...yeah. I put it in main Brigade repo bc the Contributor Guide is in there but I think it makes sense in the community repo too. Either works IMO! Would we want to move the Contributor Guide along with it?

**Comment by krancour** [comment]
> Would we want to move the Contributor Guide along with it?

This has been discussed and just hasn't happened yet.

If anyone wants to take on the busy work of replacing the contributor guide in various brigadecore projects with a link to a contributor guide in the community repo, I would owe that person all the 🍻 .

**Comment by carolynvs** [comment]
I think that adding the ladder first to the community repo would be a good start. i.e. closing this PR and making a new one for community with the ladder. 

I can help do a sweep to move more into community and update links in the respective repos so that people can find it.

**Comment by krancour** [comment]
@carolynvs is coming for all the 🍻 !

**Comment by carolynvs** [comment]
> She who writes the docs, gets the final word.

_Ancient Tech Writer Proverb_

**Pull request merged**
