### PR TITLE
feat(*): parity for brigade.json defaults/fallbacks

### PR DESCRIPTION
**Pull request by vdice**
**What this PR does / why we need it**:
Provides defaults/fallbacks for a `brigade.json` config file to match the current forms for a `brigade.js` script.

Closes https://github.com/brigadecore/brigade/issues/1020

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by radu-matei** [comment]
`handlebars`...

**Comment by vdice** [comment]
> handlebars...

:sob: @radu-matei -> https://github.com/brigadecore/brigade/pull/1027

**Comment by krancour** [comment]
@vdice I've been using this feature successfully for a few weeks-- including live at KubeCon. Is this close to mergeable?

**Comment by vdice** [comment]
@krancour thanks for the reminder.  Indeed - It's all ready for review.   Also note the related charts PR in https://github.com/brigadecore/charts/pull/53

**Pull request merged**
