### PR TITLE
chore(LICENSE): update license to Apache 2.0 per CNCF

### PR DESCRIPTION
**Pull request by vdice**
Updates License to [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) per CNCF guidelines.

Requires approval from all core maintainers as mentioned in the [CODEOWNERS](https://github.com/brigadecore/brigade/blob/master/CODEOWNERS) file:

@technosophos @adamreese @mumoshu @radu-matei @lukepatrick

See https://github.com/brigadecore/brigade/issues/957

Similar PRs will be issued in the other applicable brigadecore org repos once this initial PR gains approval.

### CODE REVIEW

**Comment by krancour** [comment]
fyi... quick search of this project shows numerous other mentions of the MIT license. This includes docs, `package.json`, and swagger spec.

**Comment by vdice** [comment]
Oops, thank you @krancour .  Added further amendments -- let me know if there are still places needing updating.

**Comment by krancour** [comment]
LGTM :shipit:

**Comment by vdice** [comment]
Ping @technosophos and @adamreese for review.  Thanks!

**Pull request merged**
