### PR TITLE
[docs] add anchor links for deep linking to section titles

### PR DESCRIPTION
**Pull request by flynnduism**
As requested by @radu-matei on [#12](https://github.com/brigadecore/brigade-www/issues/12).

This PR auto inserts anchor links to any section titles, which will appear on mouseover:
 
titles

### CODE REVIEW

**Comment by radu-matei** [comment]
This looks great, thanks a lot, Ronan!

The Netlify preview seems to be broken right now:
image

**Comment by flynnduism** [comment]
@radu-matei weird issue with the deploy preview. The way hugo is rendering the `{{ $style.Permalink }}` results in 

```<link rel="stylesheet" href="https://docs.brigade.sh/scss/theme.min.83308868dbeaaab9b99176cdfde01c900c3b77e680efaf2ba717f4853ae19a4c.css" emotion="🤩">```

This works fine in local dev and in prod, but the site previews are broken. Will file as a separate issue - this preview issue should not impact the live site.

**Comment by radu-matei** [comment]
Is there anything blocking this going forward?

**Comment by technosophos** [comment]
Are we good merging this now? I reviewed and it looks good.

**Comment by flynnduism** [comment]
@radu-matei this is good to proceed

I will create a separate ticket for the issues where site preview stylesheets break when you make css changes to the site.

**Pull request merged**
