### PR TITLE
Update installation command to Helm 3

### PR DESCRIPTION
**Pull request by itowlson**
**What this PR does / why we need it**: Updates the installation command in the Intro documentation to Helm 3, because Helm 3 is the recommended version for people to use, and the syntaxes are different

**Special notes for your reviewer**: None

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by krancour** [comment]
@itowlson LGTM, but you'll have to amend the commit with the `--signoff` flag to satisfy the DCO requirement.

**Comment by itowlson** [comment]
Done - sorry, was a quick hack via the GitHub UI - that will teach me...!

**Comment by krancour** [comment]
Thanks @itowlson !

**Comment by krancour** [comment]
Looks like we're experiencing some unrelated issues with our CI that we need to sort out.

**Review by krancour — APPROVED** [review]
Pending CI, LGTM

**Pull request merged**
