### PR TITLE
Link to contributing guide in Community repo

### PR DESCRIPTION
**Pull request by karenhchu**
Please merge https://github.com/brigadecore/community/pull/14 first.

### CODE REVIEW

**Comment by krancour** [comment]
@karenhchu can we just delete this `CONTRIBUTING.md` altogether and link directly to the one in the community repo from this repo's README.md?

**Comment by karenhchu** [comment]
@carolynvs – can you share more about why we're doing it this way?

**Comment by carolynvs** [comment]
I recommend keeping a contributing.md file in each repo. GitHub keys off of it and will do things like tell you to read it on your first PR.

**Comment by krancour** [comment]
> I recommend keeping a contributing.md file in each repo. GitHub keys off of it and will do things like tell you to read it on your first PR.

TIL ☝️ 

Thanks @carolynvs

**Review by krancour — APPROVED** [review]

**Comment by karenhchu** [comment]
FYI I'm not sure if the patch got applied to `master` but I went ahead and submitted another PR directly for 'master'.

**Pull request merged**
